name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Run Unit Tests
        run: npm run test
      - name: Run Test Coverage
        run: pnpm run test:coverage
      - name: Build Library
        run: pnpm run build
